name = "flickr-heatmap-do"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "HEATMAP_SNAPSHOT"
class_name = "HeatmapSnapshot"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["HeatmapSnapshot"]
